modLoader="javafml"
loaderVersion="[31,)" 
license="All Rights Reserved unless otherwise explicitly stated"

[[mods]]
modId="lasermod"
version="1.16-0.1_mp-patch"
displayName="KOWI's Laser Mod"
logoFile="logo.png"
authors="KOWI2003"
description="A Mod that adds working lasers and laser related items to minecraft"

[[dependencies.lasermod]]
    modId="forge"
    mandatory=true 
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lasermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16, 1.16.3, 1.16.4, 1.16.5]"
    ordering="NONE"
    side="BOTH"
